package ie.ucd.bdic.group6.core.common;

/**
 * Stable machine-readable codes for {@link OperationResult} failures.
 */
public enum OperationError {
    CARD_NOT_IN_HAND,
    CARD_NOT_IN_BANK,
    CARD_NOT_ON_PROPERTY_BOARD,
    ROW_NOT_OWNED_BY_PLAYER,
    ROW_FULL,
    WILD_COLOR_INVALID,
    PROPERTY_TYPE_MISMATCH,
    BANK_REJECTS_CARD,
    CANNOT_BANK_PROPERTY_CARD,
    CANNOT_BANK_RAINBOW_WILD,
    INSUFFICIENT_BANK_VALUE,
    NO_BANK_CARD_MEETS_MINIMUM_PAYMENT,
    RECEIVER_ROW_REJECTS_CARD,
    ROLLBACK_FAILED,
    NOT_COMPLETE_SET,
    RAIL_OR_UTILITY_CANNOT_BUILD,
    HOUSE_ALREADY_BUILT,
    HOTEL_ALREADY_BUILT,
    HOUSE_REQUIRED_BEFORE_HOTEL,
    WRONG_ACTION_CARD_TYPE,
    EMPTY_DECK,
    HAND_LIMIT_EXCEEDED,
    PROPERTY_ROW_NOT_FOUND,
    PROPERTY_CANNOT_PAY_DEBT,
    CANNOT_STEAL_FROM_COMPLETE_SET,
    DRAW_PILE_NOT_EMPTY,
    EMPTY_DISCARD_PILE,
    GENERIC
}
